language: ruby
rvm:
  - 2.0.0
script: rake travis
bundler_args: --path _vendor/bundle
gemfile: Gemfile
env:
  global:
    secure: |-
      q17geOV/9E+PEzKK5LtAVvuuH089zNsty83En3dI4FX+0KjGvUpHO8YB18R6
      5kWFqHH9SVSgl5pLWpasrKDvOIOZcPaLtIcTI+GdC2UaOn5Q16+JztTQpzJm
      s9KtEgCCpnWXujcW5oo31QDlpS53n1g/2wPCbCQon4iKFY3idgA=
